[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node node_modules/prisma/build/index.js migrate deploy && node node_modules/tsx/dist/cli.mjs prisma/seed.ts && npm run start"
healthcheckPath = "/login"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
